name: Deploy to DigitalOcean

on:
  push:
    branches: [ "main" ]  # <--- FÃ­jate que "push" tiene 2 espacios y "branches" tiene 4.

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸš€ Conectando y Desplegando
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/TREGAl_Tires_System
            
            # Reset para evitar conflictos
            git fetch --all
            git reset --hard origin/main
            
            # Actualizar dependencias
            source venv/bin/activate
            pip install -r requirements.txt
            python3 fix_db.py
            
            # --- EL TRUCO MAESTRO ---
            # 1. Aseguramos que systemd reconozca cambios
            systemctl daemon-reload
            
            # 2. Usamos --no-block para que GitHub no espere a la "muerte" del proceso
            systemctl restart tregal --no-block
            
            echo "âœ… Â¡Orden de reinicio enviada!"